function tiles2(){
  if(levelEdit){
    if(selEdit>=0){
       if(blocks[selEdit].type==6){
         push();
         strokeWeight(10)
         stroke(0);
         fill(255,0,0);
         textSize(20)
         text(blocks[selEdit].range,blocks[selEdit].bx+blocks[selEdit].bsx/2+15,blocks[selEdit].by);
         text(blocks[selEdit].delay,blocks[selEdit].bx-blocks[selEdit].bsx/2-15,blocks[selEdit].by);
         pop();
      }
      if(blocks[selEdit].type==10||blocks[selEdit].type==11||blocks[selEdit].type==12){
         push();
         strokeWeight(10)
         stroke(0);
         fill(255,0,0);
         textSize(20)
         text(blocks[selEdit].range,blocks[selEdit].bx+blocks[selEdit].bsx/2+15,blocks[selEdit].by);
         text(blocks[selEdit].delay,blocks[selEdit].bx-blocks[selEdit].bsx/2-15,blocks[selEdit].by);
         pop();
      }
      if(blocks[selEdit].type==7){
         push();
         strokeWeight(10)
         stroke(0);
         fill(255,0,0);
         textSize(20)
         text(blocks[selEdit].delay,blocks[selEdit].bx,blocks[selEdit].by+blocks[selEdit].bsy/2+15);
         pop();
      }
      if(blocks[selEdit].type==8){
         push();
         strokeWeight(10)
         stroke(0);
         fill(255,0,0);
         textSize(20)
         text(blocks[selEdit].range,blocks[selEdit].bx,blocks[selEdit].by+blocks[selEdit].bsy/2+15);
         pop();
      }
    }
  }
}